#!/bin.bash
#SBATCH --job-name=LTH_graph
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --gpus=1
#SBATCH -t 0-00:10:00
#SBATCH --cpus-per-task=18
#SBATCH -o LTH_graph.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate slck


read -p "Cuda: " cuda
read -p "Dataset: " d
read -p "Model: " model
read -p "seed: " seed

density="0.05 0.10 0.20 0.40"

for dense in $density; do
    python3 main.py --arch_type $model --data $d --seed $seed --density $dense --gpu $cuda
done